### ISSUE TITLE
Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones

### ISSUE THREAD

**Issue by mdurrant** [winauth/winauth#269]
I started getting this error this morning on the 3.4 beta build when trying to open trade confirmations for Steam. It's a blocking error and doesn't allow me to view & confirm trades.

```
Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.

   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
   at WinAuth.SteamClient.GetString(String url, String method, NameValueCollection formdata, NameValueCollection headers)
   at WinAuth.SteamClient.GetConfirmations()
   at WinAuth.ShowSteamTradesForm.Process(String username, String password, String captchaId, String captchaText)
```

**Comment by winauth** [comment]
Can you try [3.4.9](https://winauth.com/downloads/3.x/WinAuth-3.4.9.zip) if you aren't already. If you still get the issue, can you send me the winauth.log file that should get created in the same folder.

**Comment by winauth** [comment]
Think I've fixed this (again) in latest. [3.4.13](https://winauth.com/downloads/3.x/WinAuth-3.4.13.zip)
