### ISSUE TITLE
Trade confirmation on Steam

### ISSUE THREAD

**Issue by LeoHDgaming** [winauth/winauth#293]
everytime I try to confirm my trades, I put my login details than click next, than I get this problem.

Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section.

   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   at System.Net.HttpRequestCreator.Create(Uri Uri)
   at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
   at WinAuth.SteamClient.GetString(String url, String method, NameValueCollection formdata, NameValueCollection headers)
   at WinAuth.SteamClient.Login(String username, String password, String captchaId, String captchaText)
   at WinAuth.ShowSteamTradesForm.Process(String username, String password, String captchaId, String captchaText)
   at WinAuth.ShowSteamTradesForm.loginButton_Click(Object sender, EventArgs e)
   at WinAuth.ShowSteamTradesForm.ShowSteamTradesForm_KeyPress(Object sender, KeyPressEventArgs e)
   at System.Windows.Forms.Control.OnKeyPress(KeyPressEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.TabControl.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at MetroFramework.Controls.MetroTextBox.PromptedTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Than I click on continue and it drags me back to the login details page, please help ASAP cuz I wanna trade!

**Comment by winauth** [comment]
Can you look at this page, http://stackoverflow.com/questions/5168880/error-creating-the-web-proxy-specified-in-the-system-net-defaultproxy-configur, and first move WinAuth to a normal hard drive if it isn't on one already.

If still not working, create a file called winauth.exe.config, and put this in it:

```
<?xml version="1.0"?>
<configuration>
<system.net>
    <defaultProxy enabled="false" useDefaultCredentials="false">
    </defaultProxy>
  </system.net>
</configuration>


```

**Comment by LeoHDgaming** [comment]
I moved it to the C drive and made a notepad called winauth.exe.config and added all these stuff u told me to, Yet it's still not working...

**Comment by LeoHDgaming** [comment]
After making the config I've got a new error: The underlying connection was closed: Unable to connect to the remote server.

   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
   at WinAuth.SteamClient.GetString(String url, String method, NameValueCollection formdata, NameValueCollection headers)
   at WinAuth.SteamClient.Login(String username, String password, String captchaId, String captchaText)
   at WinAuth.ShowSteamTradesForm.Process(String username, String password, String captchaId, String captchaText)
   at WinAuth.ShowSteamTradesForm.loginButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at MetroFramework.Controls.MetroButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Please help.

**Comment by winauth** [comment]
I guess you are  going through a proxy? Are you able to try without it and
see if it works?

**Comment by LeoHDgaming** [comment]
I am not? :O

**Comment by winauth** [comment]
No, or you don't know? Run Internet Explorer, Click the Options menu (cog icon), Connections tab, LAN Settings, make sure Proxy server is unticked. Also try unticking "Automatically detect settings".

**Comment by LeoHDgaming** [comment]
Yup they're unticked, still same problem.

**Comment by winauth** [comment]
Ok, well, it's an odd error because it almost sounds like malware is intercepting your internet traffic or your machine is pointing to an proxy that isn't responding. Have you scanned recently?

Suggestions in other places have been to reset your network settings:

1. Bring up a command prompt with admin permissions (select Start button, type cmd in to search bar, then right click the Cmd program and select Run As Administrator)
2. Type in "netsh winsock reset" (without quotes) and press enter
3. Once the command has run, you should see the message "Winsock reset completed successfully"
4. Restart your machine and try running the launcher again.
5. Try Again. Also try running WinAuth "As Administrator".

**Comment by winauth** [comment]
You're not using in "--proxy http://some-address" for WinAuth are you?

**Comment by LeoHDgaming** [comment]
Omg thanks! it worked! I love you so much man!
