### ISSUE TITLE
windows auth error , help me i cant play dota2

### ISSUE THREAD

**Issue by emoansbert7** [winauth/winauth#375]
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at WinAuth.WinAuthConfig.ReadXml(XmlReader reader, String password)
   at WinAuth.WinAuthHelper.LoadConfig(Form form, String configFile, String password)
   at WinAuth.WinAuthForm.<>c__DisplayClass31_0.<loadConfig>b__0()

**Comment by winauth** [comment]
Winauth.xml file is corrupt. Restore from backup.
