### ISSUE TITLE
Steam connect issue

### ISSUE THREAD

**Issue by 2860192198** [winauth/winauth#386]
WinAuth won't connect to steam and in turn crashes

`2016-06-06 06:13:17.8230 3.5.0.9 WinAuth.SteamClient GET	https://steamcommunity.com/mobileconf/conf?p=android%3a08e7909d-0d8a-4f69-a6c8-ce5a90895ed5&a=76561198176618562&k=Q5SDD%2bGmEs6Xg5pVuHmAVCTxvRo%3d&t=1465208007&m=android&tag=conf	Cookies:mobileClientVersion=3067969+%282.1.3%29&mobileClient=android&steamid=&steamLogin=76561198176618562%7C%7C54AF3C24A705C2945631EB1E5E9479F22E054F4A&Steam_Language=english&dob=&sessionid=b6f19d8537b053da2d3c19ee&steamCountry=US%7Cdc38a2a4543f39d4a1921f7c82e11d82&steamMachineAuth76561198176618562=11E95A0C70490E5B6100FA72B2AACCDF4387D5EF&steamLoginSecure=76561198176618562%7C%7C84029AA134C13651BA1B4D830302ABAC97C47E13 &p=android:08e7909d-0d8a-4f69-a6c8-ce5a90895ed5&a=76561198176618562&k=Q5SDD+GmEs6Xg5pVuHmAVCTxvRo=&t=1465208007&m=android&tag=conf  System.Net.WebException: The remote name could not be resolved: 'steamcommunity.com'
   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
`

**Comment by winauth** [comment]
> The remote name could not be resolved: 'steamcommunity.com'

Possibly your side. Check your internet and DNS servers.
