### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by PowerGamer1** [winauth/winauth#392]
From time to time I am getting error message in the winauth.log:
```
2016-07-02 23:23:51.3433 3.5.1.2 WinAuth.SteamClient GET	https://steamcommunity.com/mobileconf/conf? ...
System.Net.WebException: Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.
   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
```

**Comment by winauth** [comment]
Notice any effect in WinAuth itself?

Can you send the full log, or go into About -> Diagnostics, and post the text from the box.

**Comment by PowerGamer1** [comment]
I didn't notice any effects, WinAuth itself seems to be working just fine.
You encrypt the info in About -> Diagnostics and I don't see what exactly is contained there, so I'd rather not post it here.

**Comment by winauth** [comment]
No problem.

It contains log info and authenticator data. You can email it directly to me if want, winauth@gmail.com

**Comment by PowerGamer1** [comment]
So it looks like every time I start WinAuth, select "Confirmations..." in the rightclick menu the error appears in the log immediately before the confirmations window shows up on the screen.

**Comment by winauth** [comment]
Can you send the log file then.

**Comment by PowerGamer1** [comment]
```
2016-07-03 18:45:33.8363 3.5.1.2 WinAuth.SteamClient GET	https://steamcommunity.com/mobileconf/conf?p=android%3ab...1d5&a=...&k=34...%3d&t=1...6&m=android&tag=conf
Cookies:mobileClientVersion=3067969+%282.1.3%29&mobileClient=android&steamid=&Steam_Language=english&dob=&sessionid=494...770&steamCountry=...%7C7...4c9&steamMachineAuth7...7=C2...C1 &p=android:b82...1d5&a=...&k=34K...ka8=&t=1...6&m=android&tag=conf
System.Net.WebException: Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.
   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)

2016-07-03 18:50:45.2713 3.5.1.2 WinAuth.SteamClient GET	https://steamcommunity.com/mobileconf/conf?p=android%3ab...1d5&a=...&k=y...4%3d&t=1...7&m=android&tag=conf
Cookies:mobileClientVersion=3067969+%282.1.3%29&mobileClient=android&steamid=&Steam_Language=english&dob=&sessionid=49...70&steamCountry=...%7C...c9&steamMachineAuth7...7=C2...C1 &p=android:b8...d5&a=...&k=yU...e4=&t=1...7&m=android&tag=conf
System.Net.WebException: Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.
   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
```

Here are the last two entries from the log. I replaced with "..." all values that looked like they may hold private info. I completely removed value of "a" parameter, the value of "steamid" and "dob" parameters was empty in the log. For the rest of parameters I replaced with "..." only a part of the value. Hope that helps.
